# Generated by Django 5.0.6 on 2024-07-02 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default=11, verbose_name='متن'),
            preserve_default=False,
        ),
    ]
