# Generated by Django 5.0.6 on 2024-07-13 06:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
