# Generated by Django 5.0.6 on 2024-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='value',
            field=models.PositiveIntegerField(default=1000, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
