# Generated by Django 5.0.6 on 2024-07-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_price_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('days',)},
        ),
    ]
