# Generated by Django 5.0.6 on 2024-07-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_price_name_en_price_name_fa_price_value_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('days',), 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterField(
            model_name='price',
            name='days',
            field=models.PositiveSmallIntegerField(verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.PositiveIntegerField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value_en',
            field=models.PositiveIntegerField(null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value_fa',
            field=models.PositiveIntegerField(null=True, verbose_name='value'),
        ),
    ]
