# Generated by Django 5.0.6 on 2024-07-18 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_alter_price_options_alter_price_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
