# Generated by Django 5.0.6 on 2024-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_price_created_price_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('days',), 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.RemoveField(
            model_name='price',
            name='created',
        ),
        migrations.RemoveField(
            model_name='price',
            name='updated',
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
