# Generated by Django 5.0.6 on 2024-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('username', models.CharField(max_length=60, verbose_name='نام کامل')),
                ('is_active', models.BooleanField(default=False, verbose_name='کاربر فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایچاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
