# Generated by Django 5.0.6 on 2024-07-04 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ویژه تا'),
            preserve_default=False,
        ),
    ]
