# Generated by Django 5.0.6 on 2024-07-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_full_name_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='premium_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ویژه تا'),
        ),
    ]
