# Generated by Django 5.0.6 on 2024-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_favorites'),
        ('posts', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='posts.post'),
        ),
    ]
