# Generated by Django 5.0.6 on 2024-07-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='شغل'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_fa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='شغل'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_en',
            field=models.CharField(max_length=60, null=True, verbose_name='نام کاربری'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_fa',
            field=models.CharField(max_length=60, null=True, verbose_name='نام کاربری'),
        ),
    ]
